version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - setup_remote_docker:   # (2)
        #     docker_layer_caching: true # (3)

      # create application war
      - run:
          name: Build Artifact
          command: |
                  cd webapp-backend
                  mvn package
                  mv target/webapp-backend.jar ../
      # build the application image
      - run: docker build -t $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 .
      # Login to docker hub with credentials
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      # deploy the image
      - run: docker push $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
