apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-autoscaler
  namespace: api
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: kubernetes-node-server-replicaset
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 5
