apiVersion: rbac.authorization.k8s.io/v1beta1
# This role binding allows "service account" to read secrets, nodes, configmap in the "ui" namespace.
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: api # This only grants permissions within the "ui" namespace.
subjects:
- kind: ServiceAccount
  name: backend-service-account
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io