version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      # build the application image
      - run: docker build -t $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 .

      # Login to docker hub with credentials
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      # deploy the image
      - run: docker push $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1